export const MODULES = [
  'Trabalhista',
  'Contábil',
  'Ambiental',
  'Tributário',
  'Imobiliário',
  'Civil',
  'Fiscal',
  'Recursos Humanos',
  'Administrativo',
  'Jurídico',
];

export const MODULE_COLORS = {
  'Trabalhista':      'bg-blue-100 text-blue-800 border-blue-200',
  'Contábil':         'bg-purple-100 text-purple-800 border-purple-200',
  'Ambiental':        'bg-emerald-100 text-emerald-800 border-emerald-200',
  'Tributário':       'bg-orange-100 text-orange-800 border-orange-200',
  'Imobiliário':      'bg-yellow-100 text-yellow-800 border-yellow-200',
  'Civil':            'bg-gray-100 text-gray-800 border-gray-200',
  'Fiscal':           'bg-red-100 text-red-800 border-red-200',
  'Recursos Humanos': 'bg-pink-100 text-pink-800 border-pink-200',
  'Administrativo':   'bg-slate-100 text-slate-800 border-slate-200',
  'Jurídico':         'bg-indigo-100 text-indigo-800 border-indigo-200',
};

export const DOCUMENT_TYPES = [
  'CCIR',
  'ITR',
  'Georreferenciamento',
  'Matrícula do Imóvel',
  'Escritura',
  'Certidão de Zoneamento',
  'Certidão Negativa de Débitos',
  'Certidão de Registro de Imóveis',
  'Certidão de Inteiro Teor',
  'Declaração de Aptidão ao Pronaf (DAP/CAF)',
  'Declaração de Uso e Cobertura',
  'Declaração de Produtor Rural',
  'Declaração de Movimentação de Animais (DMA)',
  'Declaração',
  'Termo de Compromisso',
  'Requerimento',
  'Identidade (RG)',
  'CPF',
  'CNPJ',
  'Comprovante de Residência',
  'Nota Fiscal',
  'Comprovante de Pagamento',
  'Procuração',
  'Alvará',
  'Outro',
];